# 1. Construct an image X with diagonal edges.

In [4]:
import torch

def corr2d(X,K):
    h,w = K.shape
    Y = torch.zeros(X.shape[0]-h+1, X.shape[1]-w+1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i+h, j:j+w]*K).sum()
    return Y

K = torch.tensor([[1.0,-1.0]])
X = torch.eye(6,8)
X

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.]])

## 1.1 What happens if you apply the kernel K in this section to it?

In [8]:
corr2d(X, K)

tensor([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [-1.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0., -1.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0., -1.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -1.,  1.,  0.]])

## 1.2 What happens if you transpose X?

In [9]:
corr2d(X.T, K)

tensor([[ 1.,  0.,  0.,  0.,  0.],
        [-1.,  1.,  0.,  0.,  0.],
        [ 0., -1.,  1.,  0.,  0.],
        [ 0.,  0., -1.,  1.,  0.],
        [ 0.,  0.,  0., -1.,  1.],
        [ 0.,  0.,  0.,  0., -1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

## 1.3 What happens if you transpose K?

In [7]:
corr2d(X, K.T)

tensor([[ 1., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1., -1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1., -1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1., -1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1., -1.,  0.,  0.]])

# 2. Design some kernels manually.

## 2.1 Given a directional vector $\vec{v}=(v_1,v_2)$, derive an edge-detection kernel that detects edges orthogonal to $\vec{v}$, i.e., edges in the direction $(v_2,-v_1)$.

In [68]:
torch.fliplr(pic)

tensor([[0., 0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 0., 0., 0.],
        [0., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.]])

In [64]:
K = torch.tensor([[1,-1],[-1,1]])
K

tensor([[ 1, -1],
        [-1,  1]])

In [69]:
corr2d(torch.fliplr(pic),K)

tensor([[ 0.,  0.,  0.,  1., -1.,  0., -1.],
        [ 0.,  0.,  1., -1.,  0., -1.,  1.],
        [ 0.,  1., -1.,  0., -1.,  1.,  0.],
        [ 1., -1.,  0., -1.,  1.,  0.,  0.],
        [-1.,  0., -1.,  1.,  0.,  0.,  0.]])

In [41]:
import torch

# Create a sample 2D matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]], dtype=torch.float32)

# Define the rotation angle in degrees
angle_degrees = 90

# Convert the angle to radians
angle_radians = torch.deg2rad(torch.tensor(angle_degrees))

# Define the rotation matrix
rotation_matrix = torch.tensor([[torch.cos(angle_radians), -torch.sin(angle_radians)],
                                [torch.sin(angle_radians), torch.cos(angle_radians)]])

# Perform the rotation using matrix multiplication
rotated_matrix = torch.mm(rotation_matrix, matrix)

print("Original matrix:")
print(matrix)
print("Rotated matrix:")
print(rotated_matrix)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 3x3)

In [37]:
pic = torch.roll(X, shifts=[2],dims=[1])+torch.roll(X, shifts=[1],dims=[1])+X
pic

tensor([[1., 1., 1., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 1., 1., 1., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0.],
        [0., 0., 0., 0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 1., 1., 1.]])

In [40]:
v = [2,2]
K = torch.eye(*v)
if v[0]*v[1] > 0:
    K = torch.fliplr(K)
K

tensor([[0., 1.],
        [1., 0.]])

In [39]:
corr2d(pic,K)

tensor([[1., 2., 1., 1., 0., 0., 0.],
        [1., 1., 2., 1., 1., 0., 0.],
        [0., 1., 1., 2., 1., 1., 0.],
        [0., 0., 1., 1., 2., 1., 1.],
        [0., 0., 0., 1., 1., 2., 1.]])

In [24]:
torch.diag(torch.tensor([1,2,3]), diagonal=0 )

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [29]:
torch.fliplr(torch.diag(torch.tensor([1,2,3]), diagonal=0 ))

tensor([[0, 0, 1],
        [0, 2, 0],
        [3, 0, 0]])

## 2.2 Derive a finite difference operator for the second derivative. What is the minimum size of the convolutional kernel associated with it? Which structures in images respond most strongly to it?


## 2.3 How would you design a blur kernel? Why might you want to use such a kernel?

## 2.4 What is the minimum size of a kernel to obtain a derivative of order 
?

# 3. When you try to automatically find the gradient for the Conv2D class we created, what kind of error message do you see?



# 4. How do you represent a cross-correlation operation as a matrix multiplication by changing the input and kernel tensors?